### ISSUE TITLE
After HDR video playback, Live Display reverts the color profile from sRGB to the default.

### ISSUE THREAD

**Issue by i-force-quit** [PixelExperience/android-issues#278]
## Build date

```
RQ3A.210605.005
PixelExperience_Plus_beryllium-11.0-20210622-0854-OFFICIAL
```

## Expected Behavior

```
The color profile should revert to what the user set, in my case, sRGB.
```

## Current Behavior

```
It reverts to the stock (dynamic) colour profile, despite the fact that the live display shows it as sRGB but it isn't. It will show sRGB in the settings, but it is not in the sRGB profile; you can confirm this by changing the colour profile back to sRGB.
```

## Possible Solution

```
The device has a mediocre display, disable hdr colour space altogether if possible.
```

## Steps to Reproduce

```
1. Set color profile to sRGB from Live Display
2. Play any HDR video from Youtube in fullscreen mode
3. Go back and check the Live display settings
4. Select sRGB to see the difference
```

/device beryllium
/version eleven_plus

**Comment by i-force-quit** [comment]
[livedisplay.txt](https://github.com/PixelExperience/android-issues/files/6744986/livedisplay.txt)

**Comment by jjpprrrr** [comment]
This is the intended behavior. The color profile setting in LiveDisplay simply loads the selected screen calibration profile. When playing an HDR video, your phone automatically loads the default profile because it offers a wider color gamut. The current implementation does not offer a way of reverting back to your previous profile after quitting the HDR video playback.

If you have a better solution, feel free to submit a PR (if it's on the device side) or push to (PE gerrit)[https://gerrit.pixelexperience.org/]

**Comment by jjpprrrr** [comment]
Actually I've tested the color profile in LiveDisplay again, and the screen does return to the previously selected color mode on `polaris (Xiaomi Mi MIX 2s)`. beryllium should behave the same.

**Comment by jjpprrrr** [comment]
I spent more than a week investigating this issue, and it appears that the color profile will return to the bottom-most srgb profile in qdcm calibration configs, no matter which profile you were on before the HDR video. There really isn't anything I can do about it.

**Comment by jjpprrrr** [comment]
Actually, I think I just fixed it.

https://gerrit.pixelexperience.org/c/hardware_qcom-caf_sdm845_display/+/12785

**Comment by i-force-quit** [comment]
It's great to hear that; it was a really vexing bug, especially when using the light theme. 😊
