### ISSUE TITLE
battery drain and pixel launcher problem

### ISSUE THREAD

**Issue by roshangurjar19** [PixelExperience/android-issues#4013]
## Build date

PixelExperience_Plus_sweet-13.0-20221130-1303-OFFICIAL.zip

## Expected Behavior

working finely as previous build

## Current Behavior

battery drain very fast and pixel launcher lag problem

## Possible Solution

may be battery optimization

## Steps to Reproduce

1.battery optimization
2. os optimization
3. app optimization
4. and so

/device sweet
/version thirteen_plus

**Comment by JakeChambersOy** [comment]
Possible fix that works for me on Cepheus:
uninstall updates for the system app "Android System Intelligence".
Since then all issues are gone. Disabling it worked too, but that caused some features to not function correctly.

Additional info:
According to various reddit posts from stock Pixel users and a google bugreport 
https://support.google.com/pixelphone/thread/188916139/pixel-launcher-extreme-cpu-usage-causing-overheating-battery-drain-and-throttling?hl=en 
this is a Google related issue, probably not specific to PixelExperience.

**Comment by jhenrique09** [comment]
We will try to fix that with gapps update on December update.

**Comment by captain-7** [comment]
did your problem get solved ? 
could i also flash in my device ?

**Comment by roshangurjar19** [comment]
Yes after uninstalling update of  Android system intelligence and reboot phone my problem is solved

**Comment by captain-7** [comment]
> Yes after uninstalling update of Android system intelligence and reboot phone my problem is solved

Did u update after that ? My battery is only draining in night when it's below 30%, If it is more than 30% then there will be no drain...
